### PR TITLE
Add development & release process for CWL

### PR DESCRIPTION
**Pull request by tetron**
Submitted for approval by the leadership team.

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
I can't request a review from Brandi Davis-Dusenbery yet, as she needs to accept the invitation I sent to join the @common-workflow-language organization. In the mean time I'll tag her here: @bdusenbery

**Review by geoffjentry — APPROVED** [review]

**Review by jmchilton — COMMENTED** [review]
Awesome - very clear, readable. Thanks for putting this together.

**Comment by mr-c** [comment]
@jmchilton I agree! Can you mark the PR as 'approved'?

**Review by jmchilton — APPROVED** [review]

**Comment by jmchilton** [comment]
Meant to do that - clicked the wrong radio button. You'd think I know how to use Github at this point.

**Comment by mr-c** [comment]
Presumably @tetron approves this process as well, so we now have a simple majority. We can wait and see if @hmenager @stain or @bdusenbery have any comments

**Comment by tetron** [comment]
Pretty sure I can't actually be a reviewer on my own PR anyway.  Guess this means it is time to make the PR for 1.2, then?

**Review by hmenager — APPROVED** [review]

**Pull request merged**
